### ISSUE TITLE
No package identifier when getting value for resource number 0x00000000

### ISSUE THREAD

**Issue by LitlleEugene** [smanikandan14/ThinDownloadManager#100]
Problem with download xls files, 

> 03-22 08:21:23.999 13794-13794/com.vk.eugenerps.webfragment W/art: Before Android 4.1, method int android.support.v7.widget.ListViewCompat.lookForSelectablePosition(int, boolean) would have incorrectly overridden the package-private method in android.widget.ListView
03-22 08:21:24.907 13794-14026/com.vk.eugenerps.webfragment W/System: ClassLoader referenced unknown path: /system/framework/tcmclient.jar
03-22 08:21:24.997 13794-14026/com.vk.eugenerps.webfragment D/ThinDownloadManager: cleanupDestination() deleting /storage/emulated/0/TimetableUC/2017/Raspad.xlsx
03-22 08:21:25.002 13794-13794/com.vk.eugenerps.webfragment W/ResourceType: No package identifier when getting value for resource number 0x00000000
03-22 08:21:25.002 13794-13794/com.vk.eugenerps.webfragment D/AndroidRuntime: Shutting down VM
03-22 08:21:25.004 13794-13794/com.vk.eugenerps.webfragment E/AndroidRuntime: FATAL EXCEPTION: main
                                                                              Process: com.vk.eugenerps.webfragment, PID: 13794
                                                                              Theme: themes:{}
                                                                              android.content.res.Resources$NotFoundException: String resource ID #0x0
                                                                                  at android.content.res.Resources.getText(Resources.java:336)
                                                                                  at android.widget.TextView.setText(TextView.java:4422)
                                                                                  at com.vk.eugenerps.webfragment.MainActivity$1.onProgress(MainActivity.java:97)
                                                                                  at com.thin.downloadmanager.DownloadRequestQueue$CallBackDelivery$4.run(DownloadRequestQueue.java:82)
                                                                                  at android.os.Handler.handleCallback(Handler.java:739)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                  at android.os.Looper.loop(Looper.java:148)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:5461)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by smanikandan14** [comment]
From stacktrace looks like this crash is not related the `ThinDownloadManager` library.

**Comment by smanikandan14** [comment]
Please check this line number. `com.vk.eugenerps.webfragment.MainActivity$1.onProgress(MainActivity.java:97)`
