### ISSUE TITLE
java.security.cert.CertPathValidatorException: Trust anchor for certification path not found

### ISSUE THREAD

**Issue by maphongba008** [smanikandan14/ThinDownloadManager#101]
I've got an issue when download a https url
 W/System.err: javax.net.ssl.SSLHandshakeException: goteam.
 W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:357)
 W/System.err:     at com.android.okhttp.internal.http.SocketConnector.connectTls(SocketConnector.java:212)
 W/System.err:     at com.android.okhttp.Connection.connect(Connection.java:1322)
 W/System.err:     at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:1410)
 W/System.err:     at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:131)
 W/System.err:     at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:484)
 W/System.err:     at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:465)
 W/System.err:     at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:371)
 W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:468)
 W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:410)
 W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:532)
 W/System.err:     at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
 W/System.err:     at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:25)
 W/System.err:     at com.thin.downloadmanager.DownloadDispatcher.executeDownload(DownloadDispatcher.java:136)
 W/System.err:     at com.thin.downloadmanager.DownloadDispatcher.run(DownloadDispatcher.java:84)
 W/System.err: Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
 W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:337)
 W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:231)
 W/System.err:     at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:115)
 W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:643)
 W/System.err:     at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
 W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:353)
 W/System.err: 	... 14 more
 W/System.err: Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
 W/System.err: 	... 20 more
Is there anyway to fix it?

**Comment by mannummm11** [comment]
Hi ,

Have you gotten any solution??

**Comment by noangel** [comment]
https://github.com/smanikandan14/ThinDownloadManager/issues/107
