### ISSUE TITLE
Unable to download mp4 file

### ISSUE THREAD

**Issue by Himanshu4003** [smanikandan14/ThinDownloadManager#18]
Here is my code:

````Java
DownloadRequest mDownloadRequest=new DownloadRequest(mUri);

            mDownloadRequest.setDestinationURI(destinationUri);

            mDownloadRequest.setDownloadListener(new DownloadStatusListener() {
                @Override
                public void onDownloadComplete(int i) {


                    mHashVideos.put(mGetFileName,destinationUri.getPath());

                    //notifyDataSetChanged();

                }

                @Override
                public void onDownloadFailed(int i, int i1, String s) {

                }

                @Override
                public void onProgress(int i, long l, int i1) {


                    LogUtil.w("LOG_TAG","Downloading Progresss-->");

                    mDownloadingPosition=mPosition;

                    //notifyDataSetChanged();


                }
            });

            mDownloadRequest.setPriority(DownloadRequest.Priority.HIGH);



             final int DOWNLOAD_THREAD_POOL_SIZE = 2;
            DownloadManager mDownloadManager=new ThinDownloadManager(DOWNLOAD_THREAD_POOL_SIZE);



            int mDownloadId=mDownloadManager.add(mDownloadRequest);
````

But it  give me following crash logs.

````
java.lang.NullPointerException
            at com.thin.downloadmanager.DownloadDispatcher.transferData(DownloadDispatcher.java:208)
            at com.thin.downloadmanager.DownloadDispatcher.executeDownload(DownloadDispatcher.java:124)
            at com.thin.downloadmanager.DownloadDispatcher.run(DownloadDispatcher.java:79)
````

What could be issue ?

**Comment by smanikandan14** [comment]
How have you integrated the library ? Have you added the dependency in build.gradle file 'compile 'com.mani:thindownloadmanager:1.0.0'. This points to old library. Use the thindownloadmanager project as library dependency in ur your project.

**Comment by Himanshu4003** [comment]
I resolved issue ,It 's due to destination url in which my root directory is not created.
