### ISSUE TITLE
array index out of range

### ISSUE THREAD

**Issue by DevendraSingh91** [smanikandan14/ThinDownloadManager#23]
08-23 18:31:07.916  28593-28744/com.emahapolitician.forchange V/ThinDownloadManager﹕ Response code obtained for downloaded Id 1 : httpResponse Code 200
08-23 18:31:07.916  28593-28744/com.emahapolitician.forchange D/ThinDownloadManager﹕ cleanupDestination() deleting /storage/emulated/0/PMK/Talking_Dog1.3gp
08-23 18:31:07.921  28593-28744/com.emahapolitician.forchange V/ThinDownloadManager﹕ Content Length: 698665 for Download Id 1
08-23 18:31:08.656  28593-28593/com.emahapolitician.forchange D/AndroidRuntime﹕ Shutting down VM
08-23 18:31:08.666  28593-28593/com.emahapolitician.forchange E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.emahapolitician.forchange, PID: 28593
    java.lang.ArrayIndexOutOfBoundsException: length=2; index=4
            at android.widget.AbsListView$RecycleBin.addScrapView(AbsListView.java:8664)
            at android.widget.ListView.layoutChildren(ListView.java:1652)
            at android.widget.AbsListView.onLayout(AbsListView.java:2627)
            at android.view.View.layout(View.java:16695)
            at android.view.ViewGroup.layout(ViewGroup.java:5328)
            at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:562)
            at android.view.View.layout(View.java:16695)
            at android.view.ViewGroup.layout(ViewGroup.java:5328)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
            at android.view.View.layout(View.java:16695)
            at android.view.ViewGroup.layout(ViewGroup.java:5328)
            at android.support.v7.internal.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:493)
            at android.view.View.layout(View.java:16695)
            at android.view.ViewGroup.layout(ViewGroup.java:5328)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
            at android.view.View.layout(View.java:16695)
            at android.view.ViewGroup.layout(ViewGroup.java:5328)
            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1702)
            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1556)
            at android.widget.LinearLayout.onLayout(LinearLayout.java:1465)
            at android.view.View.layout(View.java:16695)
            at android.view.ViewGroup.layout(ViewGroup.java:5328)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
            at android.view.View.layout(View.java:16695)
            at android.view.ViewGroup.layout(ViewGroup.java:5328)
            at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2319)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2032)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1191)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6642)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)
            at android.view.Choreographer.doCallbacks(Choreographer.java:590)
            at android.view.Choreographer.doFrame(Choreographer.java:560)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:145)
            at android.app.ActivityThread.main(ActivityThread.java:5942)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1388)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1183)

**Comment by smanikandan14** [comment]
The stack trace says the exception is in ListView.
```
java.lang.ArrayIndexOutOfBoundsException: length=2; index=4
at android.widget.AbsListView$RecycleBin.addScrapView(AbsListView.java:8664)
at android.widget.ListView.layoutChildren(ListView.java:1652)
at android.widget.AbsListView.onLayout(AbsListView.java:2627)
```

Where does it related to ThinDownloadManager ??

**Comment by DevendraSingh91** [comment]
Ohh.. Would you please impact what can I do to avoid that. Coz there is no
any line number so I thought it is issue in library. And the issue comes
when I click download button of the download manager, the progress runs for
2-3 seconds, than Unfortunately stopped error, and this stacktrace. So I
can't even find my issue.
And off course this issue arise only on "click on download button, "

**Comment by smanikandan14** [comment]
If you could share the code snippet in gist about how you are using the library and the usage of listview i can take a look at it.

**Comment by DevendraSingh91** [comment]
//gist.github.com/DevendraSingh91/ad50bf13e35b3f1a764e

**Comment by DevendraSingh91** [comment]
//gist.github.com/DevendraSingh91/ad50bf13e35b3f1a764e
this is the adapter gist which  am using 
plz help me in sorting this issue

**Comment by DevendraSingh91** [comment]
Hi,
In debug mode I got this issue,
The error code is 1004,n msg is IO.exception.
What should I do now,

**Comment by DevendraSingh91** [comment]
My bad! It was listview's error.
