### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by maohieng** [smanikandan14/ThinDownloadManager#25]
java.lang.NullPointerException
            at com.thin.downloadmanager.DownloadDispatcher.transferData(DownloadDispatcher.java:232)
            at com.thin.downloadmanager.DownloadDispatcher.executeDownload(DownloadDispatcher.java:141)
            at com.thin.downloadmanager.DownloadDispatcher.run(DownloadDispatcher.java:83)

**Comment by smanikandan14** [comment]
Looks like you are using old version of library. Please download the jar version 1.0.1 (https://github.com/smanikandan14/ThinDownloadManager/raw/master/library-jar/thindownloadmanager-1.0.1.jar)

**Comment by DVassilev** [comment]
@smanikandan14 I am using the latest jar and I am getting that error too.
