### ISSUE TITLE
Create destination if it doesn't exist

### ISSUE THREAD

**Issue by DVassilev** [smanikandan14/ThinDownloadManager#33]
Hello,

A good enhancement would be for the library to create the destination folder if it does not exist as currently I get the following error if it doesn't exist.

```
java.lang.NullPointerException
       at com.thin.downloadmanager.DownloadDispatcher.transferData(DownloadDispatcher.java:232)
       at com.thin.downloadmanager.DownloadDispatcher.executeDownload(DownloadDispatcher.java:141)
       at com.thin.downloadmanager.DownloadDispatcher.run(DownloadDispatcher.java:83)
```

Thanks,
Daniel

**Comment by smanikandan14** [comment]
Added a fix for it in version 1.2.1. Please use the updated version in build.gradle.
