### ISSUE TITLE
errorCode:1004:errorMessage:Trouble with low-level sockets

### ISSUE THREAD

**Issue by pop1030123** [smanikandan14/ThinDownloadManager#34]
i meet errorCode:1004:errorMessage:Trouble with low-level sockets when download .what does is mean?

**Comment by smanikandan14** [comment]
When establishing connection with server, if anything above 400 is returned by server, httpurlconnection throws IOException. And this log is thrown. 

Check this link. 
http://stackoverflow.com/questions/21990677/httpurlconnection-getresponsecode-throws-ioexception-when-code-is-known

**Comment by smanikandan14** [comment]
I am closing this issue. I hope this issue is not related to the library itself. Could be problem with connection to server.

**Comment by Sel-en-ium** [comment]
For me, I received this error when this error was thrown:

```
W/System.err: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:357)
W/System.err:     at com.android.okhttp.internal.http.SocketConnector.connectTls(SocketConnector.java:212)
W/System.err:     at com.android.okhttp.Connection.connect(Connection.java:1322)
W/System.err:     at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:1410)
W/System.err:     at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:131)
W/System.err:     at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:484)
W/System.err:     at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:465)
W/System.err:     at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:371)
W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:476)
W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:418)
W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:540)
W/System.err:     at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
W/System.err:     at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:25)
W/System.err:     at com.thin.downloadmanager.DownloadDispatcher.executeDownload(DownloadDispatcher.java:136)
W/System.err:     at com.thin.downloadmanager.DownloadDispatcher.executeDownload(DownloadDispatcher.java:162)
W/System.err:     at com.thin.downloadmanager.DownloadDispatcher.run(DownloadDispatcher.java:84)
W/System.err: Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:337)
W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:231)
W/System.err:     at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:115)
W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:643)
W/System.err:     at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:353)
W/System.err: 	... 15 more
W/System.err: Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
```
