### ISSUE TITLE
DownloadDispatcher.transferData() may crash with a nullpointer exception

### ISSUE THREAD

**Issue by nibarius** [smanikandan14/ThinDownloadManager#44]
DownloadDispatcher.transferData() may crash with a nullpointer exception as such:

    java.lang.NullPointerException: Attempt to invoke virtual method 'void java.io.OutputStream.close()' on a null object reference
        at com.thin.downloadmanager.DownloadDispatcher.transferData(DownloadDispatcher.java:232)
        at com.thin.downloadmanager.DownloadDispatcher.executeDownload(DownloadDispatcher.java:141)
        at com.thin.downloadmanager.DownloadDispatcher.run(DownloadDispatcher.java:83)

The problem lies in the finally block at the end of the method

```java
try {
    if (out != null) out.flush();
    if (outFd != null) outFd.sync();
} catch (IOException e) {
} finally {
	try {
		out.close();
	} catch (IOException e) {
		e.printStackTrace();
	}
}
```

out is normally checked against null before used, but in the finally block there is no check so if out is null it will crash here.

**Comment by nibarius** [comment]
Ignore me, seems like this is fixed in the latest code. Just that the version I'm running doesn't have the fix.
