### ISSUE TITLE
Attempt to invoke virtual method 'void java.io.OutputStream.write(byte[], int, int)' on a null object reference

### ISSUE THREAD

**Issue by alirezaaa** [smanikandan14/ThinDownloadManager#46]
Hi,

I'm getting following error, 'Attempt to invoke virtual method 'void java.io.OutputStream.write(byte[], int, int)' on a null object reference'.

```
ClassName
com.thin.downloadmanager.DownloadDispatcher / com.thin.downloadmanager.DownloadDispatcher / com.thin.downloadmanager.DownloadDispatcher / com.thin.downloadmanager.DownloadDispatcher / com.thin.downloadmanager.DownloadDispatcher /
MethodName
writeDataToDestination / transferData / transferData / executeDownload / run /
LineNumber
296 / 276 / 220 / 144 / 83 /
```

**Comment by smanikandan14** [comment]
Fixed this crash in version 1.2.1. Please update the version in your gradle file.

**Comment by pawegio** [comment]
Still occurs in 1.2.1:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void java.io.OutputStream.write(byte[], int, int)' on a null object reference
        at com.thin.downloadmanager.DownloadDispatcher.writeDataToDestination(DownloadDispatcher.java:315)
        at com.thin.downloadmanager.DownloadDispatcher.transferData(DownloadDispatcher.java:295)
        at com.thin.downloadmanager.DownloadDispatcher.transferData(DownloadDispatcher.java:238)
        at com.thin.downloadmanager.DownloadDispatcher.executeDownload(DownloadDispatcher.java:142)
        at com.thin.downloadmanager.DownloadDispatcher.run(DownloadDispatcher.java:81)
```

**Comment by Aiuspaktyn** [comment]
Still occurs in 1.2.2:

```
Fatal Exception: java.lang.NullPointerException
       at com.thin.downloadmanager.DownloadDispatcher.writeDataToDestination(SourceFile:315)
       at com.thin.downloadmanager.DownloadDispatcher.transferData(SourceFile:295)
       at com.thin.downloadmanager.DownloadDispatcher.transferData(SourceFile:238)
       at com.thin.downloadmanager.DownloadDispatcher.executeDownload(SourceFile:142)
       at com.thin.downloadmanager.DownloadDispatcher.run(SourceFile:81) 
```

**Comment by smanikandan14** [comment]
I fixed this issue yesterday. Could you try vesion ```1.2.3```
