### ISSUE TITLE
Divide by 0

### ISSUE THREAD

**Issue by josemssilva** [smanikandan14/ThinDownloadManager#6]
Hi.

Having troubles downloading some files, apparently if the file is served from a redirect I get a 'Divide by 0' error.

java.lang.ArithmeticException: divide by zero
            at com.thin.downloadmanager.DownloadDispatcher.transferData(DownloadDispatcher.java:231)
            at com.thin.downloadmanager.DownloadDispatcher.transferData(DownloadDispatcher.java:193)
            at com.thin.downloadmanager.DownloadDispatcher.executeDownload(DownloadDispatcher.java:124)
            at com.thin.downloadmanager.DownloadDispatcher.run(DownloadDispatcher.java:79)

Any clues?

Thanks in advance.

**Comment by smanikandan14** [comment]
Fixed this issue.
