### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by mouness2020** [smanikandan14/ThinDownloadManager#63]
i love your library but i have this problem...why this Exception happen??
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException
       at com.android.okio.Util.checkOffsetAndCount(Util.java:29)
       at com.android.okio.OkBuffer.getByte(OkBuffer.java:161)
       at com.android.okio.OkBuffer.readUtf8Line(OkBuffer.java:322)
       at com.android.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:96)
       at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:175)
       at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:101)
       at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:616)
       at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:379)
       at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:323)
       at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:491)
       at com.thin.downloadmanager.DownloadDispatcher.executeDownload(DownloadDispatcher.java:131)
       at com.thin.downloadmanager.DownloadDispatcher.run(DownloadDispatcher.java:81)

**Comment by PrimeKang** [comment]
I'm wondering if [this](https://community.oracle.com/thread/2426315?start=0) is the same issue. 
 -If you have control of the file host, are you able to disable http chunking? 
 -What version of Android are you running on? Is this reproducible with a recent version of Android? Preferably marshmallow, but I'm confident lollipop should also be fine based on the patch-date of the suspected issue.
