### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by Aiuspaktyn** [smanikandan14/ThinDownloadManager#99]
compile 'com.mani:ThinDownloadManager:1.3.0'

**I can not reproduce this bug**

`Fatal Exception: java.lang.OutOfMemoryError: pthread_create (stack size 16384 bytes) failed: Try again
       at java.lang.VMThread.create(VMThread.java)
       at java.lang.Thread.start(Thread.java:1029)
       at java.util.Timer$TimerImpl.(Timer.java:192)
       at java.util.Timer.(Timer.java:367)
       at java.util.Timer.(Timer.java:387)
       at java.util.Timer.(Timer.java:394)
       at com.thin.downloadmanager.DownloadDispatcher.run(SourceFile:74)`

**Comment by TapanM** [comment]
Same issue coming
